services:
  - type: web
    name: case-monitor
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt && playwright install --with-deps chromium"
    startCommand: "python monitor_render.py"
    envVars:
      - key: WC_ID_1
        sync: false
      - key: WC_PASS_1
        sync: false
      - key: WC_ID_2
        sync: false
      - key: WC_PASS_2
        sync: false
      - key: GMAIL_ADDRESS
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: GCP_SERVICE_ACCOUNT
        sync: false
